[package]
name = "labserver"
version = "0.1.0"
authors = ["sivertjoe <sivert-joh@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.8.0"
serde_json = "*"
serde_derive = "*"
serde = "*"
